# The Site Configuration

# Import the theme
theme: minima
# remote_theme: cotes2020/jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Kathmandu

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Aarati Mahato # the main title

tagline: Flutter Developer # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Skilled Flutter developer with a passion for creating functional and visually appealing mobile applications. Portfolio of projects showcasing expertise in Flutter, Python, HTML, and CSS.

# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://aaratimahato.com.np"

github:
  username: nilumahato # change to your github username

twitter:
  username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Aarati Mahato
  email: aaratimahato00@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/nilumahato # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Minima theme settings
author:
  name: Aarati Mahato
  email: aaratimahato00@gmail.com

# Simple navigation
header_pages:
  - about.md

# Basic site settings
title: Aarati Mahato # the main title
tagline: Flutter Developer # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Skilled Flutter developer with a passion for creating functional and visually appealing mobile applications. Portfolio of projects showcasing expertise in Flutter, Python, HTML, and CSS.

# Fill in the protocol & hostname for your site.
url: "https://aaratimahato.com.np"
baseurl: ""

# GitHub info
github:
  username: nilumahato

# Author info for minima theme
author:
  name: Aarati Mahato
  email: aaratimahato00@gmail.com

# Simple navigation
header_pages:
  - about.md

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Aarati Mahato

# Basic pagination
paginate: 10
paginate_path: "/page:num/"

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

# Basic pagination
paginate: 10
paginate_path: "/page:num/"

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
