# The Site Configuration

# Import the theme
theme: minima

# Basic site info
title: Aarati Mahato
description: >-
  Skilled Flutter developer with a passion for creating functional and visually appealing mobile applications. 
  Portfolio of projects showcasing expertise in Flutter, Python, HTML, and CSS.

# Site URL
url: "https://aaratimahato.com.np"
baseurl: ""

# GitHub Pages settings
lang: en
timezone: Asia/Kathmandu

# Author info
author:
  name: Aarati Mahato
  email: aaratimahato00@gmail.com

# GitHub info
github_username: nilumahato

# Navigation
header_pages:
  - about.md

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Build settings
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - package*.json
  - README.md
  - LICENSE
